<a href="https://colab.research.google.com/github/arturcgs/BootcampDataScienceAplicada3/blob/main/Projeto%20Final/Projeto_Final_Funcoes_e_Limpeza_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bem vindo!

Este Notebook é dedicado ao **projeto final do BootCamp Data Science Aplicada 3**, da Alura. 

Neste projeto, será analisado o banco de dados clínicos de pacientes do Sírio Libanês, disponível no [Kaggle](https://www.kaggle.com/S%C3%ADrio-Libanes/covid19). O objetivo deste banco de dados é gerar um modelo que preveja se um paciente de COVID-19 precisará ser internado na UTI. Para isso, diversos dados clínicos são disponibilizados, como sexo, idade, doenças pré-existentes, resultados de exames de sangue, entre outros.

# Importações

Primeiramente, as bilbiotecas a serem utilizadas são importadas

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.feature_selection import VarianceThreshold

from scipy.stats import randint

from time import perf_counter

#Definição de Funções

In [59]:
#Pra usar somente a primeira linha, vamos mudar a UTI da window 0-2 pra 1 se o paciente foi pra UTI em qualquer momento e deixar 0 se ele n foi

def prepare_window(rows):
  '''DataFrameGroupBy --> DataFrame Row

  -----------------------------------------------------------------------------
  
  Esta função recebe um DataFrameGroupBy. Ela irá, então
  avaliar as linhas deste Groupby. Se este paciente, em algum
  momento, foi para a UTI, ela muda a primeira janela para 1. Caso contrário, 
  a primeira janela permanece 0. A função então devolve a primeira janela'''

  if np.any(rows["ICU"]) == 1:
      rows.loc[rows['WINDOW'] == "0-2", "ICU"] = 1
  return rows.loc[rows['WINDOW'] == "0-2"]

In [76]:
def remove_corr_alta(dados_completos, dados_continuos, alta_corr):
  '''DataFrame, DataFrame, int --> DataFrame

  -----------------------------------------------------------------------------

  Esta função recebe um banco de dados completo, um banco de dados só com
  variáveis contínuas e um valor limite de correlação
  Ela, então, irá selecionar uma, de cada par de variáveis que tenham 
  correlação mais alta que o limiar. A função retorna o df sem essas variáveis'''

  #Fazendo a matriz de correlação
  matriz_corr = dados_continuos.corr().abs()

  #Selecionando somente o triângulo superior dos dados
  matriz_tri_sup = matriz_corr.where(np.triu(np.ones(matriz_corr.shape), k = 1).astype(bool))

  #Selecionando as variáveis a serem deletadas
  excluir = []

  for coluna in matriz_tri_sup.columns:
    if any(matriz_tri_sup[coluna] > alta_corr):
      excluir.append(coluna)  
  
  print(f'Foram excluídos {len(excluir)} parâmetros')

  return dados_completos.drop(excluir, axis = 1)

In [61]:
def best_params_randomized(x, y, model_params, n_splits=5, n_repeats=10, n_iter=20):
  '''DataFrame, DataFrame, Dictionary, int, int, int --> DataFrame

  -----------------------------------------------------------------------------

  Esta função recebe dois DataFrames, um de variáveis para os modelos (x)
  e outro de alvo (y). Ela também recebe um dicionário, contendo os modelos
  e seus parâmetros a serem testados. Como a função realiza RepeatedStratifiedKFold,
  valores de n_splits e n_repeats também podem ser passados. Finalmente, n_iter
  também pode ser definido, para o RandomizedSearchCV.
  A função, então, irá executar o RandomizedSearchCV em todos os modelos e parâmetros
  informados e retornará um DataFrame com o melhor resultado e parâmetros de cada
  modelo.'''

  t0 = perf_counter()
  np.random.seed(3126831)

  cv = RepeatedStratifiedKFold(n_splits = n_splits, n_repeats = n_repeats)
  scores = []

  for model_name, mp in model_params.items():
      clf =  RandomizedSearchCV(mp['model'], mp['params'], cv=cv,
                                return_train_score=False, scoring = 'roc_auc',
                                n_iter = n_iter)
      clf.fit(x, y)
      scores.append({
          'model': model_name,
          'best_score': clf.best_score_,
          'best_params': clf.best_params_
      })

  result = pd.DataFrame(scores,columns=['model','best_score','best_params'])

  t1 = perf_counter() - t0
  print(f'Tempo de execução: {(t1/60): 0.3f}')

  return result

In [62]:
def best_params_grid(x, y, model_params, n_splits=5, n_repeats=10):
  '''DataFrame, DataFrame, Dictionary, int, int --> DataFrame

  -----------------------------------------------------------------------------

  Esta função recebe dois DataFrames, um de variáveis para os modelos (x)
  e outro de alvo (y). Ela também recebe um dicionário, contendo os modelos
  e seus parâmetros a serem testados. Como a função realiza RepeatedStratifiedKFold,
  valores de n_splits e n_repeats também podem ser passados.
  A função, então, irá executar o GridSearchCV em todos os modelos e parâmetros
  informados e retornará um DataFrame com o melhor resultado e parâmetros de cada
  modelo.'''

  t0 = perf_counter()
  np.random.seed(37865)

  cv = RepeatedStratifiedKFold(n_splits = n_splits, n_repeats = n_repeats)
  scores = []
  resultado = {}

  for model_name, mp in model_params.items():
      clf =  GridSearchCV(mp['model'], mp['params'], cv=cv,
                                return_train_score=False, scoring = 'roc_auc')
      clf.fit(x, y)
      scores.append({
          'model': model_name,
          'best_score': clf.best_score_,
          'best_params': clf.best_params_
      })

      resultado[model_name] = pd.DataFrame(clf.cv_results_)
      
  result = pd.DataFrame(scores,columns=['model','best_score','best_params'])
  t1 = perf_counter() - t0
  print(f'Tempo de execução: {(t1/60): 0.3f}')
  return result

# Limpeza de Dados

## Limpeza Geral

A pesar dos dados já virem arrumados, facilitando sua importação, ainda há muita limpeza a ser feita. Inicialmente, uma limpeza geral é realizada. Neste etapa, os seguintes processos são feitos:


1. Importação dos dados
2. Preenchimentos de NaNs

Para preencher os NaNs, existem diversas técnicas. Neste caso, é razoável assumir que um paciente, em uma janela em que não foi coletado seus dados, permanece clinicamente estável. Desta maneira, podemos preencher este dado faltando com as janelas vizinhas. Aqui, então, foi aplicado o método de backward e forward fill para preencher os NaNs.

In [77]:
#Importando os dados

dados = pd.read_excel('https://github.com/arturcgs/BootcampDataScienceAplicada3/blob/main/Bancos_de_Dados/Sirio_Libanes_ICU_Kaggle.xlsx?raw=true')
dados.head()

   PATIENT_VISIT_IDENTIFIER  AGE_ABOVE65  ...    WINDOW  ICU
0                         0            1  ...       0-2    0
1                         0            1  ...       2-4    0
2                         0            1  ...       4-6    0
3                         0            1  ...      6-12    0
4                         0            1  ...  ABOVE_12    1

[5 rows x 231 columns]

In [78]:
#Preenchendo os NaNs

#Separando features

features_continuas_colunas = dados.iloc[:, 13:-2].columns
features_categoricas = dados.iloc[:, :13]
saida = dados.iloc[:, -2:]

#Agrupando os dados contínuos e preenchendo seus NaNs

features_continuas = dados.groupby("PATIENT_VISIT_IDENTIFIER", as_index=False)[features_continuas_colunas].fillna(method='bfill').fillna(method='ffill')

#Juntar tudo em um df só

dados_limpos = pd.concat([features_categoricas, features_continuas, saida], ignore_index = True, axis = 1)
dados_limpos.columns = dados.columns

#Tirando oq sobrou de NaN

dados_limpos = dados_limpos.dropna()

## Ajuste de Pacientes para interpretação mais fácil dos modelos

Aqui, três técnicas foram aplicadas:


1. Retirar pacientes que foram direto à UTI
2. Selecionar somente a janela 0-2 dos pacientes
3. Tranformação da variável AGE_PERCENTIL em categórica

A importância de retirar os pacientes que foram direto à UTI a seguinte: a janela em que o paciente foi à UTI não pode ser utilizada. Isso ocorre porque, como o paciente pode ter ido à UTI em qualquer momento dentro daquela janela, é impossível sabe se os exames daquela janela foram realizados antes ou depois do paciente ir à UTI. Como nosso modelo quer prever se o paciente vai ou nâo à UTI, não faz sentido utilizar exames feitos com ele na UTI. Portanto, se o paciente foi à UTI na primeira janela, não podemos utilizar seus dados.

A seleção da janela 0-2 tem dois motivos para ser realizada: Facilitação de interpretação dos dados pelo modelo e maior relevância dessa janela. O modelo consegue interpretar mais facilmente os dados se cada paciente está representado somente em uma linha. Adicionalmente, em uma situação real no hospital, é necessário entender se o paciente precisará de UTI ou não ou mais cedo possível. Desta maneira, treinar o modelo somente com dados da primeira janela gera previsões mais relevantes.

Finalmente, os modelos não interpretam dados em string, portante a variável AGE_PERCENTIL deve ser transformada em variável categórica.

In [79]:
#Retirando pacientes que foram direto pra UTI

a_remover = dados_limpos.query("WINDOW == '0-2' and ICU == 1")["PATIENT_VISIT_IDENTIFIER"].values

dados_limpos = dados_limpos.query("PATIENT_VISIT_IDENTIFIER not in @a_remover")

In [80]:
#Selecionando somente a janela 0-2 de cada paciente. 
#Se o paciente foi para a UTI em outro momento, esta janela é mudada para 1
#Caso contrário, ela permanece 0

dados_limpos = dados_limpos.groupby('PATIENT_VISIT_IDENTIFIER').apply(prepare_window)

#Como todos os pacientes estão na janela 0-2, ela pode ser eliminada do df
dados_limpos = dados_limpos.drop(['WINDOW'], axis = 1)

In [81]:
#Transformando AGE_PERCENTIL em variável categórica

dados_limpos.AGE_PERCENTIL = dados_limpos.AGE_PERCENTIL.astype("category").cat.codes

dados_limpos.head()

                             PATIENT_VISIT_IDENTIFIER  ...  ICU
PATIENT_VISIT_IDENTIFIER                               ...
0                        0                          0  ...    1
2                        10                         2  ...    1
3                        15                         3  ...    0
4                        20                         4  ...    0
5                        25                         5  ...    0

[5 rows x 230 columns]

## Retirando variáveis com variância 0

Uma variável que permanece constante em toda a extenção dos dados é irrelevante na construção de um modelo. Portanto, para facilitar cálculos, essas variáveis são retiradas.

In [82]:
#Tirando parâmetros q têm baixa variância

var_thres = VarianceThreshold(threshold = 0)
var_thres.fit(dados_limpos)

constant_columns = [column for column in dados_limpos.columns
                    if column not in dados_limpos.columns[var_thres.get_support()]]

dados_limpos_com_var = dados_limpos.drop(constant_columns, axis = 1)

print(f'Foram excluídos {230-sum(var_thres.get_support())} parâmetros')

Foram retirados 36 parâmetros

## Retirando variáveis com alta correlação entre si (maior que 0.95)

Variáveis muito semelhantes entre si não acrescentam na construção do modelo. Portanto, se duas variáveis têm alto correlação entre si, uma delas dele ser excluída, enquanto a outra é mantida.

In [85]:
dados_limpos_sem_corr = remove_corr_alta(dados_limpos_com_var, dados_limpos_com_var.iloc[:, 13:-1], 0.95)

Foram excluídos 131 parâmetros

In [86]:
dados_limpos_sem_corr.head()

                             PATIENT_VISIT_IDENTIFIER  ...  ICU
PATIENT_VISIT_IDENTIFIER                               ...
0                        0                          0  ...    1
2                        10                         2  ...    1
3                        15                         3  ...    0
4                        20                         4  ...    0
5                        25                         5  ...    0

[5 rows x 63 columns]

# Final

Este notebook realizou a importação de bibliotecas relevantes, definição de funções a serem utilizadas e limpeza do banco de dados. 

A Análise Exploratória a criação de modelos foi realizada [neste notebook](https://github.com/arturcgs/BootcampDataScienceAplicada3/blob/main/Projeto%20Final/Projeto_Final.ipynb)