<a href="https://colab.research.google.com/github/arturcgs/BootcampDataScienceAplicada3/blob/main/Aulas/M%C3%B3dulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
 #importando o banco de dados de gastos hospitalares, por data do procedimento
URL = 'https://raw.githubusercontent.com/arturcgs/BootcampDataScienceAplicada3/main/Bancos_de_Dados/Prod_Hosp_SUS%20-%20Atendimento.csv'
dados = pd.read_csv(URL, encoding="utf-8", 
                    skiprows = 3, sep=";", skipfooter=11, 
                    thousands=".", decimal=",")
dados.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support skipfooter; you can avoid this warning by specifying engine='python'.
  """

  Unidade da Federação 1992/Mar 1992/Abr  ... 2021/Ago 2021/Set    Total
0          11 Rondônia        -        -  ...     6192     1826  1448181
1              12 Acre        -        -  ...     2097        -   659770
2          13 Amazonas        -        -  ...    14105     7167  2361068
3           14 Roraima        -        -  ...     3239     2072   487698
4              15 Pará        -        -  ...    23036     5782  6703021

[5 rows x 293 columns]

In [8]:
#Limpando o DataFrame

#pegando somente as colunas que tem tds os campos preenchidos
colunas_usaveis = dados.mean().index.tolist()
colunas_usaveis.insert(0, "Unidade da Federação") #inserindo o índice

dados_usavel = dados[colunas_usaveis]
dados_usavel = dados_usavel.set_index("Unidade da Federação") #adicionando o índice

#tirando a coluna e linha total
dados_usavel = dados_usavel.drop("Total", axis=1)
dados_usavel = dados_usavel.drop("Total", axis=0)

dados_usavel.head()

                      2007/Ago  2007/Set  ...  2021/Jul  2021/Ago
Unidade da Federação                      ...
11 Rondônia                  7        42  ...      8130      6192
12 Acre                      5        17  ...      3391      2097
13 Amazonas                 59        69  ...     17543     14105
14 Roraima                  14         8  ...      3580      3239
15 Pará                    404       798  ...     33257     23036

[5 rows x 169 columns]

In [19]:
#Importando a tabela de população por estado da Wikipedia
populacao_por_estado = pd.read_html('https://pt.wikipedia.org/wiki/Lista_de_unidades_federativas_do_Brasil_por_popula%C3%A7%C3%A3o')[0]

#Arrumando os nomes e tirando as colunas indesejadas
populacao_por_estado['uf'] = populacao_por_estado['Unidade federativa']
populacao_por_estado['populacao'] = populacao_por_estado['População']
populacao_por_estado = populacao_por_estado.drop(['Posição', 'Unidade federativa',	'População',	'% da pop. total',	'País comparável (habitantes)'], axis=1)

#tirando os espaços q tem entre os números
populacao_por_estado['populacao'] = populacao_por_estado['populacao'].str.replace(' ', '').astype(int)

#ordenando por ordem crescente
populacao_por_estado = populacao_por_estado.sort_values('populacao', ascending=False)

populacao_por_estado.head()

               uf  populacao
0       São Paulo   46649132
1    Minas Gerais   21411923
2  Rio de Janeiro   17463349
3           Bahia   14985284
4          Paraná   11597484